Mar  4 14:18:04 kernel: _nvram_free: 1639(httpd) nvram_idx(1 / 2)
Mar  4 14:18:04 rc_service: httpd 1639:notify_rc stop_vpnc
Mar  4 14:18:04 vpnclient5[28969]: SIGTERM[hard,init_instance] received, process exiting
Mar  4 14:18:09 BWDPI: fun bitmap = 5bf
Mar  4 14:18:09 A.QoS: qos_count=0, qos_check=0
Mar  4 14:18:09 kernel: ERR[parse_qos_conf:939] Can't set new QoS conf while QoS is started!
Mar  4 14:18:09 kernel: ERR[ioctl_iqos_op_config:3608] parse qos_conf error!!
Mar  4 14:18:09 kernel: ioctl_iqos_op_config() fail!
Mar  4 14:18:09 A.QoS: set_qos_conf fails
Mar  4 14:18:09 A.QoS: restart A.QoS because set_qos_conf / set_qos_on / setup rule fail
Mar  4 14:18:10 A.QoS: qos_count=0, qos_check=1
Mar  4 14:18:49 kernel: _nvram_free: 1639(httpd) nvram_idx(0 / 2)
Mar  4 14:18:49 rc_service: httpd 1639:notify_rc restart_vpnc
Mar  4 14:18:51 vpnclient5[31178]: OpenVPN 2.4.12 aarch64-unknown-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Jan  9 2024
Mar  4 14:18:51 vpnclient5[31178]: library versions: OpenSSL 1.1.1t  7 Feb 2023, LZO 2.10
Mar  4 14:18:51 vpnclient5[31180]: NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mar  4 14:18:51 vpnclient5[31180]: TCP/UDP: Preserving recently used remote address: [AF_INET]77.91.85.31:1194
Mar  4 14:18:51 vpnclient5[31180]: Socket Buffers: R=[131072->131072] S=[16384->16384]
Mar  4 14:18:51 vpnclient5[31180]: Attempting to establish TCP connection with [AF_INET]77.91.85.31:1194 [nonblock]
Mar  4 14:18:52 vpnclient5[31180]: TCP: connect to [AF_INET]77.91.85.31:1194 failed: Connection refused
Mar  4 14:18:52 vpnclient5[31180]: SIGUSR1[connection failed(soft),init_instance] received, process restarting
Mar  4 14:18:52 vpnclient5[31180]: Restart pause, 5 second(s)
Mar  4 14:18:56 BWDPI: fun bitmap = 53f
Mar  4 14:18:57 vpnclient5[31180]: NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mar  4 14:18:57 vpnclient5[31180]: TCP/UDP: Preserving recently used remote address: [AF_INET]77.91.85.31:1194
Mar  4 14:18:57 vpnclient5[31180]: Socket Buffers: R=[131072->131072] S=[16384->16384]
Mar  4 14:18:57 vpnclient5[31180]: Attempting to establish TCP connection with [AF_INET]77.91.85.31:1194 [nonblock]
Mar  4 14:18:58 vpnclient5[31180]: TCP connection established with [AF_INET]77.91.85.31:1194
Mar  4 14:18:58 vpnclient5[31180]: TCP_CLIENT link local: (not bound)
Mar  4 14:18:58 vpnclient5[31180]: TCP_CLIENT link remote: [AF_INET]77.91.85.31:1194
Mar  4 14:18:58 vpnclient5[31180]: TLS: Initial packet from [AF_INET]77.91.85.31:1194, sid=8834e416 80afb592
Mar  4 14:18:59 vpnclient5[31180]: VERIFY ERROR: depth=1, error=self signed certificate in certificate chain: CN=AntiZapret CA, serial=188353819646654821157519000602397762517871707683
Mar  4 14:18:59 vpnclient5[31180]: OpenSSL: error:1416F086:lib(20):func(367):reason(134)
Mar  4 14:18:59 vpnclient5[31180]: TLS_ERROR: BIO read tls_read_plaintext error
Mar  4 14:18:59 vpnclient5[31180]: TLS Error: TLS object -> incoming plaintext read error
Mar  4 14:18:59 vpnclient5[31180]: TLS Error: TLS handshake failed
Mar  4 14:18:59 vpnclient5[31180]: Fatal TLS error (check_tls_errors_co), restarting
Mar  4 14:18:59 vpnclient5[31180]: SIGUSR1[soft,tls-error] received, process restarting
Mar  4 14:18:59 vpnclient5[31180]: Restart pause, 5 second(s)
Mar  4 14:19:04 vpnclient5[31180]: NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mar  4 14:19:04 vpnclient5[31180]: TCP/UDP: Preserving recently used remote address: [AF_INET]77.91.85.31:1194
Mar  4 14:19:04 vpnclient5[31180]: Socket Buffers: R=[131072->131072] S=[16384->16384]
Mar  4 14:19:04 vpnclient5[31180]: Attempting to establish TCP connection with [AF_INET]77.91.85.31:1194 [nonblock]
Mar  4 14:19:05 vpnclient5[31180]: TCP connection established with [AF_INET]77.91.85.31:1194
Mar  4 14:19:05 vpnclient5[31180]: TCP_CLIENT link local: (not bound)
Mar  4 14:19:05 vpnclient5[31180]: TCP_CLIENT link remote: [AF_INET]77.91.85.31:1194
Mar  4 14:19:05 vpnclient5[31180]: TLS: Initial packet from [AF_INET]77.91.85.31:1194, sid=5d0dea2a e43e5606
Mar  4 14:19:05 vpnclient5[31180]: VERIFY ERROR: depth=1, error=self signed certificate in certificate chain: CN=AntiZapret CA, serial=188353819646654821157519000602397762517871707683
Mar  4 14:19:05 vpnclient5[31180]: OpenSSL: error:1416F086:lib(20):func(367):reason(134)
Mar  4 14:19:05 vpnclient5[31180]: TLS_ERROR: BIO read tls_read_plaintext error
Mar  4 14:19:05 vpnclient5[31180]: TLS Error: TLS object -> incoming plaintext read error
Mar  4 14:19:05 vpnclient5[31180]: TLS Error: TLS handshake failed
Mar  4 14:19:05 vpnclient5[31180]: Fatal TLS error (check_tls_errors_co), restarting
Mar  4 14:19:05 vpnclient5[31180]: SIGUSR1[soft,tls-error] received, process restarting
Mar  4 14:19:05 vpnclient5[31180]: Restart pause, 5 second(s)
Mar  4 14:19:10 vpnclient5[31180]: NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mar  4 14:19:10 vpnclient5[31180]: TCP/UDP: Preserving recently used remote address: [AF_INET]77.91.85.31:1194
Mar  4 14:19:10 vpnclient5[31180]: Socket Buffers: R=[131072->131072] S=[16384->16384]
Mar  4 14:19:10 vpnclient5[31180]: Attempting to establish TCP connection with [AF_INET]77.91.85.31:1194 [nonblock]
Mar  4 14:19:11 vpnclient5[31180]: TCP connection established with [AF_INET]77.91.85.31:1194
Mar  4 14:19:11 vpnclient5[31180]: TCP_CLIENT link local: (not bound)
Mar  4 14:19:11 vpnclient5[31180]: TCP_CLIENT link remote: [AF_INET]77.91.85.31:1194
Mar  4 14:19:11 vpnclient5[31180]: TLS: Initial packet from [AF_INET]77.91.85.31:1194, sid=181ab06a e93edc82
Mar  4 14:19:11 vpnclient5[31180]: VERIFY ERROR: depth=1, error=self signed certificate in certificate chain: CN=AntiZapret CA, serial=188353819646654821157519000602397762517871707683
Mar  4 14:19:11 vpnclient5[31180]: OpenSSL: error:1416F086:lib(20):func(367):reason(134)
Mar  4 14:19:11 vpnclient5[31180]: TLS_ERROR: BIO read tls_read_plaintext error
Mar  4 14:19:11 vpnclient5[31180]: TLS Error: TLS object -> incoming plaintext read error
Mar  4 14:19:11 vpnclient5[31180]: TLS Error: TLS handshake failed
Mar  4 14:19:11 vpnclient5[31180]: Fatal TLS error (check_tls_errors_co), restarting
Mar  4 14:19:11 vpnclient5[31180]: SIGUSR1[soft,tls-error] received, process restarting
Mar  4 14:19:11 vpnclient5[31180]: Restart pause, 5 second(s)


