
    <html>
      <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style>
    th, td {
      border: 1px solid black;
      border-collapse: collapse;
    }
    th, td {
      word-wrap: break-word;
      padding: 5px;
    }
    table {
      width: 100%;
      max-width: 100%;
      border: 1px solid black;
      border-collapse: collapse;
      table-layout: fixed;
      word-wrap: break-word
    }
    code {
      word-wrap: break-word;
    }
    pre {
        white-space: pre-wrap;
    }
    </style>
        <title>ошибка-в-клиенте-при-подключении-к-vless-vpn-серверу</title>
      </head>
      <body>
        <table border="1" width="100%" cellpadding="5">
          <tr>
            <th style="width: 10%;">Ник</th>
            <th>Пост</th>
            <th style="width: 10%;">Дата</th>
          </tr>
    <tr><td>BMWWW(Mikhail)</td><td><p>День добрый, столкнулся с проблемой, которая не гуглится даже в зарубежном интернете и связана с подключением к моему VLESS серверу поднятому в Амстердаме.</p>
<p>О сервере: Панель 3X-UI: v2.4.4 Xray v24.11.5</p>
<p>Раннее без проблем подключался к серверу через TUN в клиенте Hiddify, но теперь начала возникать ошибка, такая же ошибка возникает в v2rayN. В любом VPN клиенте, который умеет подключаться по VLESS.  При включении TUN, чтобы весь трафик начал идти через виртуальный туннель в логах появляются вот такие ошибки:</p>
<p><code>+0700 2024-12-18 19:22:46 WARN inbound/tun[tun-in]: open tun interface take too much time to finish!</code><br>
и через пару секунд<br>
<code>FATAL[0017] start service: initialize inbound/tun[tun-in]: configure tun interface: There was no match for the specified key in the index.</code></p>
<p>Ещё в Сетевых подключениях был “x-tap-vpn” или как-то так название, я так понимаю, как раз через этот адаптер должен идти трафик при включении TUN режима в любом VPN клиенте, но он был с крестиком и не включался. Думал, что удалю его из списка адаптеров и какой-нибудь из VPN клиентов обнаружит, что адаптер пропал, переустановит его и всё заработает, но этого не произошло. Всё также возникает фатальная ошибка. Пробовал ставить на свой компьютер(Windows 10) WireGuard, VPN клиенты разные, которые ставят адаптеры но ничего не помогает…Проблема, как я понимаю, в моём ПК, а с сервером в Амстердаме всё в порядке.</p>
<p>В Гугле такой ошибки и решений нет, не знаю что делать…прошу помощи.</p>
<p>При этом, работает режим прокси в Hiddify и V2RayN. Успешно идёт подключение к моему  серверу c VLESS, но проблема в том, что через режим прокси всё в разы медленнее, чем через режим TUN(VPN). Поэтому хочу его вернуть.</p></td><td>2024-12-18T12:31:18.759Z</td></tr><tr><td>spotted_giraffe</td><td><p>Пробовали решение описанное тут?</p><aside class="onebox githubissue" data-onebox-src="https://github.com/tailscale/tailscale/issues/6461">
  <header class="source">

      <a href="https://github.com/tailscale/tailscale/issues/6461" target="_blank" rel="noopener nofollow ugc">github.com/tailscale/tailscale</a>
  </header>

  <article class="onebox-body">
    <div class="github-row">
  <div class="github-icon-container" title="Issue" data-github-private-repo="false">
	  <svg width="60" height="60" class="github-icon" viewBox="0 0 14 16" aria-hidden="true"><path fill-rule="evenodd" d="M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z"></path></svg>
  </div>

  <div class="github-info-container">
    <h4>
      <a href="https://github.com/tailscale/tailscale/issues/6461" target="_blank" rel="noopener nofollow ugc">Failed to setup adapter</a>
    </h4>

    <div class="github-info">
      <div class="date">
        opened <span class="discourse-local-date" data-format="ll" data-date="2022-11-23" data-time="14:07:50" data-timezone="UTC">02:07PM - 23 Nov 22 UTC</span>
      </div>

        <div class="date">
          closed <span class="discourse-local-date" data-format="ll" data-date="2022-11-29" data-time="14:09:24" data-timezone="UTC">02:09PM - 29 Nov 22 UTC</span>
        </div>

      <div class="user">
        <a href="https://github.com/cewei" target="_blank" rel="noopener nofollow ugc">
          <img alt="cewei" src="ошибка-в-клиенте-при-подключении-к-vless-vpn-серверу/26e3444357f15fa4692e30acbee12881dec32cae.png" class="onebox-avatar-inline" width="20" height="20" data-dominant-color="B7E4D5">
          cewei
        </a>
      </div>
    </div>

    <div class="labels">
        <span style="display:inline-block;margin-top:2px;background-color: #B8B8B8;padding: 2px;border-radius: 4px;color: #fff;margin-left: 3px;">
          needs-triage
        </span>
        <span style="display:inline-block;margin-top:2px;background-color: #B8B8B8;padding: 2px;border-radius: 4px;color: #fff;margin-left: 3px;">
          bug
        </span>
    </div>
  </div>
</div>

  <div class="github-row">
    <p class="github-body-container">### What is the issue?

Unable to create adapter

logtail started
local disk <span class="show-more-container"><a href="" rel="noopener" class="show-more">…</a></span><span class="excerpt hidden">logdir: C:\ProgramData\Tailscale\Logs
Program starting: v1.32.3-ta07555f43-g093d1e978, Go 1.19.2-ts3fd24dee31: []string{"C:\\Program Files (x86)\\Tailscale IPN\\tailscaled.exe"}
LogID: f73301be6449409dc0e7f189717bdfcdcb9b802efe68ccd0131387910c962940
logpolicy: using dir C:\ProgramData\Tailscale
wgengine.NewUserspaceEngine(tun "Tailscale") ...
Installing driver 0.14
Extracting driver
Installing driver
Creating adapter
Timed out waiting for device query: The wait operation timed out. (Code 0x00000102)
Failed to setup adapter (problem code: 0x1C, ntstatus: 0xC0000490): There was no match for the specified key in the index. (Code 0x00000491)
no TUN failure diagnostics for OS "windows"
wgengine.NewUserspaceEngine(tun "Tailscale") error: tstun.New("Tailscale"): Error creating interface: There was no match for the specified key in the index.
flushing log.
logger closing down
createEngine: tstun.New("Tailscale"): Error creating interface: There was no match for the specified key in the index.

### Steps to reproduce

Updated to the latest version of tailscale

Have uninstalled and reinstalled tailscale

### Are there any recent changes that introduced the issue?

Update to the latest version of tailscale

### OS

Windows

### OS version

Windows 10 Pro 22H2

### Tailscale version

1.32.3

### Bug report

_No response_</span></p>
  </div>

  </article>

  <div class="onebox-metadata">
    
    
  </div>

  <div style="clear: both"></div>
</aside>
</td><td>2024-12-18T15:11:35.696Z</td></tr><tr><td>BMWWW(Mikhail)</td><td><p>Да, но у меня после ввода команды в PowerShell выдаёт, что база данных повреждена и ничего не записывает в файл. Попытка восстановления базы данных и реестра через DISM не помогает. Похоже у меня серьезные проблемы с Windows, но так не хочется переставлять её, так как на ней множество всего важного. Поэтому поднял рядом Ubuntu второй системой и сижу через неё на заблокированных сайтах через Hiddify, а Windows использую для белого и пушистого браузинга</p></td><td>2024-12-26T15:00:06.940Z</td></tr>
    </table>
      </body>
    </html>